### ISSUE TITLE
Bazel rules for Clif?

### ISSUE THREAD

**Issue by tautomaton** [google/clif#1]
It'd be great to incorporate Clif into Bazel workspaces.  Will we see Skylark rules to do so?

**Comment by mrovner** [comment]
When Bazel grew support for
(a) custom C++ compilers/toolchains (CLIF is a C++ compiler) and 
(b) building python extensions
then CLIF can build Bazel integration.
So that issue better direct at Bazel project.

From what we know it's not coming anytime "soon", so I'm closing it. Feel free to reopen/contribute if that assessment is incorrect.

**Comment by davidzchen** [comment]
Seems the Bazel rules are here: https://github.com/google/clif/blob/main/clif_build_rule.bzl
