### ISSUE TITLE
Build failure on MacOS High Sierra, using LLVM5 & Python 3

### ISSUE THREAD

**Issue by dvhwgumby** [google/clif#23]
On High Sierra I installed 

    pip3 install 'pyparsing>=2.2.0'
    pip3 install virtualenv
    pip3 install virtualenvwrapper
    brew install protobuf --with-python3
    git clone https://github.com/google/clif.git
    export PATH=/usr/local/opt/llvm/bin:$PATH
    cd clif;
    ./INSTALL.sh python3

c++ and cc in /usr/local/bin (already on PATH) are symlinked to /usr/local/opt/llvm/bin/clang++ and clang respectively.

`./Install.sh python3` runs for quite a while but ultimately fails:

    _ParseError: unhashable type
    make[3]: *** [tools/clif/python/utils/proto_util.cc] Error 3
    make[2]: *** [tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/all] Error 2
    make[1]: *** [tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/rule] Error 2
    make: *** [clif_python_utils_proto_util] Error 2

I'm not sure how to proceed.

**Comment by yilei** [comment]
Would https://github.com/google/clif/issues/14#issuecomment-334846787 fix the issue?

(To be released in next version.)

**Comment by yilei** [comment]
This is likely related to using a old pyparsing version.

My current guess is that LLVM cmake uses a different Python by default, and that Python has an old pyparsing version.

Can you try adding the following to the `cmake` command here and try again? https://github.com/google/clif/blob/6c6d894a112d978bd5abfcab1052c60c5ee365a9/INSTALL.sh#L113

`-DPYTHON_EXECUTABLE="$PYTHON"`

(Otherwise also try use an absolute path for the Python interpreter, since I'm not sure it requires an absolute path or not.)

**Comment by dvhwgumby** [comment]
I see from that other thread that you don't support MacOS X so I apologize for these reports.  I tried both of those changes but no luck.

I switched to the system compiler rather than llvm 5 in the hope that would improve things, but there is some sort of include path error while generating proto_util.cc, proto_util.h, proto_util.init.cc and it is pulling in the 2.7 python libraries and headers.  I'll investigate further.  It's possible that the brew-installed protobuf is inadequate so I'll try downloading a full package manually.  Thanks @yilei.

**Comment by carine-1** [comment]
I had the same "_ParseError: unhashable type" error at compilation of proto_util.cc, while installing CLIF, on Ubuntu 14.
This was due to pyparsing NOT being upgraded to version 2.2.0 because the old version was "owned by the OS".

Solution which worked for me : 

**1- Install pyparsing version 2.2.0 as "_pyparsing 2_".** To do this I followed these steps :
  . download pyparsing module from https://sourceforge.net/projects/pyparsing/
  . extract the wheel to a local folder
  . rename pyparsing.py into _pyparsing2.py_
  . create a file _setup.py_ containing the following lines : 
`    from distutils.core import setup`
`    setup(`
`          name="Pyparsing2",`
`          version='2.2.0',`
`          description='Parse (for help type import pyparsing ; help(pyparsing))',`
`          author='Paul T. McGuire',`
`          py_modules=['pyparsing2'],`
`          )`

  . cd to the repertory where _pyparsing2.py_ and the newly created _setup.py_ are located
  . type : `sudo python setup.py install`
  
**2- Replace "import pyparsing as pp" by "import pyparsing2 as pp"** in CLIF files :
     clif-master/clif/python/pytd_parser.py
     clif-master/clif/python/pytd_parser_test.py

After this the "_ParseError" disappeared and CLIF compiled succesfully to the end.

**Comment by TTaEE** [comment]
I got this error after ./INSTALL.sh python3

Traceback (most recent call last):
  File "/Users/thananchai/anaconda3/lib/python3.6/site-packages/virtualenv.py", line 2567, in <module>
    main()
  File "/Users/thananchai/anaconda3/lib/python3.6/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/Users/thananchai/anaconda3/lib/python3.6/site-packages/virtualenv.py", line 1071, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/Users/thananchai/anaconda3/lib/python3.6/site-packages/virtualenv.py", line 1457, in install_python
    shutil.copyfile(executable, py_executable)
  File "/Users/thananchai/anaconda3/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 62] Too many levels of symbolic links: '/Users/thananchai/opt/clif/bin/python3'

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
