### ISSUE TITLE
[Feature Request] C# Generator Support

### ISSUE THREAD

**Issue by Mizux** [google/clif#26]
Since CLIF is a "C++ wrapper generators for **various** languages." and a replacement of SWIG, I would like to have the C# (.NET netstandard2.0 TFM) support...

note: For google/or-tools we may use CLIF instead of SWIG but we need the C# support first !!!

**Comment by mrovner** [comment]
Sure, C# can be supported. However Google does not use it and does not sponsor CLIF C# development. So "you need it, you do it" :) We can provide guidance and share lessons learned.

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
