### ISSUE TITLE
"First steps" fail for Windows with VS 2017

### ISSUE THREAD

**Issue by garretfick** [google/clif#29]
I'm not entirely certain I'm following the right steps, but this is what I understood from the docs.

1. Cloned the repository locally
2. Started a x86 Native Tools Command Prompt for VS 2017
3. In the command prompt, change directories to the cloned directory
4. Execute the steps from read the docs:

```
mkdir build
cd build
cmake ..
cmake --build . --config Release --target check
```
The final step gives the error:

`NMAKE : fatal error U1073: don't know how to make 'check'`

Running `cmake -version` return the following information:

```
C:\Users\USERNAME\pybind11\build>cmake -version
cmake version 3.12.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by garretfick** [comment]
I wrote this in the wrong window - and wrong project. Sorry. Feel free to delete this.

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
