### ISSUE TITLE
Multi-Module Packages Have Dependency Problems

### ISSUE THREAD

**Issue by tinskip** [google/clif#30]
I am having some trouble getting a package with inter-dependent modules to work.  Everything builds fine, but upon load of the dependent module,  I get undefined symbol errors for the dependencies.  

I put together a minimal example based on the CLIF OSS samples wrappod/wrapfunc (attached). It can be built and run via the showme.sh script from within the wrapcomb directory.  

Thanks!

[wrapcomb.zip](https://github.com/google/clif/files/2229098/wrapcomb.zip)

**Comment by udnaan** [comment]
I suspect that someone would be more willing to look at it if it was available via a git repository than a zip file.

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
