### ISSUE TITLE
clif not compatible with python3.8 due to type difference for tp_print

### ISSUE THREAD

**Issue by kkawabat** [google/clif#35]
Trying to install pykaldi on macOS Catalina for python3.8 and currently stuck on building pyclif: 

> [100%] Building CXX object tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/proto_util.cc.o

with the error:

> /Users/kkawabat/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc:314:3: error: cannot initialize a
>           member subobject of type 'Py_ssize_t' (aka 'long') with an rvalue of type 'nullptr_t'
>       nullptr,                             // tp_print
>       ^~~~~~~

I believe this is due to changes to `tp_print` for python3.8 (see footnote for [python type objects](https://docs.python.org/3.8/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall_offset)) 

> Changed in version 3.8: This slot was used for print formatting in Python 2.x. In Python 3.0 to 3.7, it was reserved and named tp_print.

it used to be of type `printfunc`  but now it's`Py_ssize_t` which cannot be typed as `nullptr`

**Comment by rwgk** [comment]
Closing ALL open issues.                                                        
                                                                                
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
